---
navs:
  - name: Tutorial
    icon: fa fa-dashboard
    isOpen: true
    badge:
      variant: info
      text: NEW
    children:
      - name: Components
        icon: fa fa-object-group
        goto: components.yml
      - name: Dashpad Api
        icon: fa fa-github
        goto: ui.yml